version: '3.5'

services:
  mongo1:
    image: mongo
    command: mongod --replSet "rs0"
    deploy:
      placement:
        constraints:
          - node.Role==Manager
    volumes:
      - mongo-data:/data/db
    networks:
      sil:
        aliases: 
          - mongo

  mongo2:
    image: mongo
    command: mongod --replSet "rs0"
    deploy:
      placement:
        constraints:
          - node.Role==Worker
    volumes:
      - mongo-data:/data/db
    networks:
      sil:
        aliases: 
          - mongo

  elasticsearch:
    image: elasticsearch:6.5.0
    hostname: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch-cluster
      - "discovery.zen.ping.unicast.hosts=tasks.elasticsearch"
      - "network.host=0.0.0.0"
      - "node.max_local_storage_nodes=2"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    networks:
      - sil
    deploy:
        mode: global
        restart_policy:
          delay: 30s
          max_attempts: 10
          window: 120s

  backend:
    image: backend
    ports:
      - 3000:3000
    command: npm start
    networks:
      - sil
    deploy:
        mode: global
        restart_policy:
          delay: 30s
          max_attempts: 10
          window: 120s

  web:
    image: web
    ports:
      - 80:80
      - 443:443
    networks:
      - sil
    deploy:
        mode: global

  manager:
    image: manager
    ports:
      - 5000:5000
    command: npm start
    networks:
      - sil
    deploy:
        mode: global
    
  admin:
    image: admin
    ports:
      - 6767:6767
    command: npm start
    networks:
      - sil
    deploy:
        mode: global

networks:
  sil:
    name: sil

volumes:
  elasticsearch-data:

  mongo-data:
